// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClj2lG-MWVLWtRUA0X4pGOlzyKrLkVw_E',
    appId: '1:257388023831:web:1100678b6000ac967c8c52',
    messagingSenderId: '257388023831',
    projectId: 'tacafe-67178',
    authDomain: 'tacafe-67178.firebaseapp.com',
    storageBucket: 'tacafe-67178.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiNU_MXf9tvlc8QhoFeRYByJE9Ws1N7h4',
    appId: '1:257388023831:android:030e71a335ec583a7c8c52',
    messagingSenderId: '257388023831',
    projectId: 'tacafe-67178',
    storageBucket: 'tacafe-67178.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh0y4bdOmZRUtdZfg2fA89qeFJNdPVdT4',
    appId: '1:257388023831:ios:63634908cb4ddfd57c8c52',
    messagingSenderId: '257388023831',
    projectId: 'tacafe-67178',
    storageBucket: 'tacafe-67178.appspot.com',
    iosClientId: '257388023831-ag9ubephr2rfhqgrc4mh2gb1ha8cvpo6.apps.googleusercontent.com',
    iosBundleId: 'com.example.tacafe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh0y4bdOmZRUtdZfg2fA89qeFJNdPVdT4',
    appId: '1:257388023831:ios:63634908cb4ddfd57c8c52',
    messagingSenderId: '257388023831',
    projectId: 'tacafe-67178',
    storageBucket: 'tacafe-67178.appspot.com',
    iosClientId: '257388023831-ag9ubephr2rfhqgrc4mh2gb1ha8cvpo6.apps.googleusercontent.com',
    iosBundleId: 'com.example.tacafe',
  );
}
